Travel html
Poberezhets/travel pull request #1
Opened 2022-07-18 15:16 UTC by Poberezhets

Создана HTML разметка сайта.

2022-07-18 20:19 UTC, eprikhodko requested changes
Отличный PR, продолжай в том же духе! :+1:  :fire: 

TO DO:

Сначала что нужно сделать тебе:
- внести правки которые я предложил сделать, ответить на некоторые вопросы, и вообще можно подискуссировать при желании
- вноси правки, и делай коммиты просто в эту же ветку, в travel-html
- не забудь посмотреть в терминале, в какой ветке ты находишься. Если ветка не travel-develop, переключись в нее командой `git switch travel-html`, вноси правки, сохраняй изменения, делай коммиты и указывай в сообщении к коммиту что то вроде `refactor: add alts to the images` или если будешь вносить много правок разом, наверное можно сказать что то вроде `refactor: make requested changes after PR review`
- удачи :wink: 

Ниже то, что нужно сделать мне:
- клонировать репозиторий к себе на комп
- запустить веб сервер в vscode
- посмотреть, как правильно прописывать пути для картинок, инфа была где то на RS School, в задании с markdown

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +    <div class="background-preview">
Тут наверное можно дать этому диву класс не background-preview, а background-wrapper, или bg-wrapper.

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +            <img src="/assets/img/icons/logo.svg" alt="logo" />
Элементу <img> можно добавить класс logo-icon.

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +        <div class="button">
Тут див наверное не обязателен и его пока можно убрать. То есть, вытащить кнопку из дива с классом button, и оставить только кнопку, а родительский див у кнопки удалить. Или обертка вокруг кнопки добавлена специально? Если да, то расскажи пожалуйста, с какой целью.

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +        <section class="preview">
Я бы назвал класс этой секции не preview, а hero-section, или promo-section.

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +            <div class="input">
Сделай лучше такую структуру: положи `<div class="input">` в тег form. То есть просто поменяй `<div class="input">` и тег form местами. Атрибуты action="#" и method="post" у формы можно пока убрать. 
```suggestion
      <form>
         <div class="input">
                <input type="search" placeholder="What would you like to do?" />
                <button class="btn input-button">Start Planning</button>
         </div>
       </form>
```

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +        <div class="ellipse">
Этому диву лучше дать класс banner-buttons.

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +          <button class="ellipse-button"></button>
Этим кнопкам класс лучше дать вида button-ellipse, то есть сначала говорим что это кнопка, а потом - какая это кнопка, в данном случае это эллипс.

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +          <img src="/assets/img/icons/arrow.png" alt="" />Find More
Картинке надо дать какой то alt, сейчас он пустой.

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +        <div class="background-stories">
Можно класс назвать просто bg-stories, для краткости.

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +                <h3>10 Photos of Attractive Thailand</h3>
Надо наверное дать h3 класс story-title

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +            <div class="story">
Можно использовать div, но лучше здесь будет использовать article. Почему? div - это элемент общего назначения, не имеющий никакого семантического значения. А судя по макету, здесь контент тянет на полноценный article. Прочти пожалуйста про article на mdn: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article), постарайся понять, в чем смысл этого элемента, и расскажи в ответном комментарии, для чего по-твоему предназначен этот элемент, как ты это поняла. В чем разница между div и article? Постарайся дать какой нибудь ответ, и напиши его здесь, в ответ на этот комментарий :wink:

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +            <img src="/assets/img/icons/arrow.png" alt="" />See More
Дай какой нибудь alt картинке. Погугли пожалуйста, кажется у img всегда должен присутствовать какой нибудь alt. Посмотри на mdn, там написано что это не обязательный атрибут, но очень нужный. Напиши в ответном комментарии, что ты узнала на mdn, почему лучше прописывать что нибудь внутри alt?

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +            <div class="social-media-icon">
Наверное класс лучше назвать social-media-icons, добавить s на конце, так как это множественное число.

2022-07-18 20:19 UTC, eprikhodko commented on index.html
> +</html>
Отличный PR, продолжай в том же духе! :+1:  :fire: 

TO DO:

Сначала что нужно сделать тебе:
- внести правки которые я предложил сделать, ответить на некоторые вопросы, и вообще можно подискуссировать при желании
- вноси правки, и делай коммиты просто в эту же ветку, в travel-html
- не забудь посмотреть в терминале, в какой ветке ты находишься. Если ветка не travel-develop, переключись в нее командой `git switch travel-html`, вноси правки, сохраняй изменения, делай коммиты и указывай в сообщении к коммиту что то вроде `refactor: add alts to the images` или если будешь вносить много правок разом, наверное можно сказать что то вроде `refactor: make requested changes after PR review`
- удачи :wink: 

Ниже то, что нужно сделать мне:
- клонировать репозиторий к себе на комп
- запустить веб сервер в vscode
- посмотреть, как правильно прописывать пути для картинок, инфа была где то на RS School, в задании с markdown

2022-07-19 11:51 UTC, Poberezhets commented on index.html
> +          <img src="/assets/img/icons/arrow.png" alt="" />Find More
Я не написала alt, так как если иконка не подгрузится, то вместо нее будет слово "arrow" и тогда кнопка будет выглядеть так " arrow Find More", что будет выглядеть странно. А если стрелка не подгрузится, то кнопка будет выглядеть "Find More", что не так странно и вполне нормально и понятно для пользователя.

2022-07-19 12:20 UTC, Poberezhets commented on index.html
> +        <section class="preview">
Я назвала так эту секцию, так как в требованиях к верстке было прописано. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/travel/travel-part1.md

2022-07-19 12:56 UTC, Poberezhets commented on index.html
> +            <div class="story">
Я прочитала, поняла что article это как статья в журнале, которая включает в себя h1-h6, поняла только это.

2022-07-19 12:58 UTC, Poberezhets commented on index.html
> +            <img src="/assets/img/icons/arrow.png" alt="" />See More
поняла что alt важен для слепых или слабовидящих людей, единственно я не поняла, нужно ли описывать не очень важные элементы.

2022-07-19 13:10 UTC, eprikhodko commented
Посмотри еще пожалуйста у тебя в картинках, в иконках, по моему arrow.png лишняя. Нужно ее наверное удалить?

2022-07-19 16:12 UTC, eprikhodko commented on index.html
> +        <section class="preview">
Точно, тогда вопросов нет, все должно соответствовать ТЗ.

2022-07-19 16:12 UTC, eprikhodko commented on index.html
> +            <div class="story">
Да, все верно. Точное определение приведено в начале статьи:

`The <article> [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a self-contained composition in a document, page, application, or site, which is intended to be independently distributable or reusable (e.g., in syndication). Examples include: a forum post, a magazine or newspaper article, or a blog entry, a product card, a user-submitted comment, an interactive widget or gadget, or any other independent item of content.`

То есть элемент `<article>`представляет собой самодостаточную, отдельную единицу какого то контента. Поэтому в контексте нашего сайта Travel, уместно наверное в этой секции использовать `<article>`, а не div.

![2022-07-19_18-55](https://user-images.githubusercontent.com/74785156/179795242-d2e14e98-4f87-47f6-9d63-71eef0455ded.png)

2022-07-19 16:12 UTC, eprikhodko commented on index.html
> +          <img src="/assets/img/icons/arrow.png" alt="" />Find More
Хороший поинт, надо потестировать это поведение. Сделаем так: откроем страницу в браузере и сломаем картинку и посмотрим, как будет вести себя alt. Может быть правда в данном случае его можно не добавлять.

2022-07-19 16:12 UTC, eprikhodko commented on index.html
> +            <img src="/assets/img/icons/arrow.png" alt="" />See More
Да, все верно. Это хороший вопрос, я и сам пока не знаю точно, стоит ли добавлять alt таким элементам, как картинка внутри этой кнопки. Пока что вопрос остается открытым, нужно поизучать. В данном контексте наверное для слепого пользователя не будет разницы, есть ли alt у иконки со стрелкой внутри кнопки, потому что он по контенту "See More" сможет понять, что делает эта кнопка. 

Но наверное, alt все равно лучше заполнить, потому что скрин ридер наверное скажет, что внутри кнопки есть какая то картинка. А что это за картинка? Слепому будет непонятно. А вдруг там что нибудь важное?

В общем, это надо у слепых пользователей наверное уточнять, нужны ли им альты в кнопках. Но я бы все равно их заполнял.

2022-07-19 16:44 UTC, Poberezhets commented on index.html
> +            <img src="/assets/img/icons/arrow.png" alt="" />See More
https://stackoverflow.com/questions/4359920/is-it-necessary-to-include-alt-in-images

2022-07-20 06:22 UTC, eprikhodko commented on index.html
> +            <img src="/assets/img/icons/logo.svg" alt="logo" />
Только убери тогда класс logo)

2022-07-20 06:24 UTC, eprikhodko commented on index.html
> +            <img src="/assets/img/icons/arrow.png" alt="" />See More
Все понял, для декоративных элементов alt может быть пустым. Тогда здесь его можно не заполнять и оставить `alt=""`

2022-07-20 09:20 UTC, eprikhodko commented on index.html
> +        <img src="/assets/img/icons/logo.svg" alt="logo" />
Поправь пожалуйста еще все пути для картинок.

Вот статья, как надо сделать, чтобы картинки отображались:

https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0-hints.md#%D0%BF%D1%83%D1%82%D0%B8

![2022-07-20_12-14](https://user-images.githubusercontent.com/74785156/179945405-59ee124b-b90b-48f5-bb53-8f0fa11e698b.png)

![2022-07-20_12-15](https://user-images.githubusercontent.com/74785156/179945440-b506e77d-639d-4b88-8de7-e9da67f90cf1.png)

Вот еще Кевин рассказывал про это:

https://scrimba.com/learn/responsive/background-images-and-the-file-path-very-important-note-c8gkm3sE

2022-07-20 10:36 UTC, eprikhodko approved these changes

2022-07-20 10:38 UTC, merged