Travel fonts
Poberezhets/travel pull request #2
Opened 2022-07-22 11:53 UTC by Poberezhets

Задача: добавить стили для шрифтов на сайт. 

![2022-07-22 14_50_22-Window](https://user-images.githubusercontent.com/74712223/180433549-efdb3fa3-538d-44d7-9ae2-87c9ed7f886f.png)

Что было сделано: 
- Подключила шрифты через google-fonts
- Добавила стили для шрифтов

2022-07-24 07:05 UTC, eprikhodko approved these changes

2022-07-24 07:05 UTC, eprikhodko commented on style.css
> +
Лишняя пустая строка откуда то вылезла. Prettier не убирает при сохранении пустые строки сам?

2022-07-24 07:06 UTC, eprikhodko commented on style.css
> +
Все отлично :+1:

2022-07-24 07:50 UTC, eprikhodko approved these changes
Все отлично :+1:

2022-07-24 07:50 UTC, eprikhodko commented on style.css
> +    font-size: 16px;
Обычно стандартный размер шрифта на странице - это 16px. То есть мы в самом начале css файла со стилями, можем сказать:

```
html {
 font-size: 16px;
}
```

И тогда у всех элементов, кроме h1-h6 будет font-size: 16px, и для кнопки не надо будет задавать отдельно font-size, если он равен 16px.

Но для h1-h6 браузер сам задает размер шрифта, в em, поэтому для заголовков font-size: 16px не будет наследоваться. Возможно для каких то других элементов браузер тоже не будет наследовать font-size.

В общем, иногда можно пользоваться таким наследованием, когда мы задаем font-size, color, font-weight для всего шрифта сразу, в html {}, тогда можно будет меньше повторяться.

Вот кстати можно правило font-weight: 500 тоже добавить в html {}

2022-07-25 10:47 UTC, Poberezhets commented on style.css
> +
Я проверила, сам не убирает при сохранении.

2022-07-25 12:12 UTC, eprikhodko requested changes

2022-07-25 12:12 UTC, eprikhodko commented on index.html
> +          <li class="list-item">
Назови пожалуйста этот класс не list-item, а nav-list-item

2022-07-25 12:12 UTC, eprikhodko commented on index.html
> +            <a class="nav-menu" href="#">How It Works</a>
Назови пожалуйста этот класс не nav-menu, потому что не понятно, почему это ссылка, а класс у нее nav-menu. Назови ее лучше nav-link.

Позови меня пожалуйста, когда будешь менять названия классов, я покажу как это быстро сделать в VS Code.

2022-07-25 12:12 UTC, eprikhodko commented on style.css
> +.nav-menu {
Тут получается тоже, название изменится с .nav-menu на .nav-link, так будет понятнее.

2022-07-25 12:20 UTC, merged